### ISSUE TITLE
uptobox.com Download Manager Adware still showing

### ISSUE THREAD

**Issue by axarad** [HandyUserscripts/AntiAdware#17] opened 2015-05-03 08:48 UTC
Hi & thanks for your time!
Download manager button still showing
here is an example of download link: http://uptobox.com/ib4i3u1vpoc3
I click "Create Download Link" and here is what I get: <a href="http://imgur.com/MMPI5i2"><img src="http://i.imgur.com/MMPI5i2.jpg" title="source: imgur.com" /></a>

**Comment by devnoname120** [comment] 2015-05-03 10:41
Duplicate of #17

**Closed** 2015-05-03 10:41 UTC
Labels: duplicate
